# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: false
      settings:
        MinVersion: '10.0.22631'
        
  resources:
  
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: false
      settings:
        Ensure: Present
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vsPackage
      directives:
        description: Install Visual Studio 2022 Community
        allowPrerelease: false
      settings:
        id: Microsoft.VisualStudio.2022.Community
        source: winget
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vscodePackage
      directives:
        description: Install Visual Studio Code
        allowPrerelease: false
      settings:
        id: Microsoft.VisualStudioCode
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: dotnetCore9
      directives:
        description: Install .NET Core 9 SDK
        allowPrerelease: false
      settings:
        id: Microsoft.DotNet.SDK.9
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: gitPackage
      directives:
        description: Install Git
      settings:
        id: Git.Git
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: githubDesktopPackage
      directives:
        description: Install GitHub Desktop
      settings:
        id: GitHub.GitHubDesktop
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: nvmPackage
      directives:
        description: Install NVM for Windows
      settings:
        id: CoreyButler.NVMforWindows
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: redisInsightPackage
      directives:
        description: Install RedisInsight
      settings:
        id: XP8K1GHCB0F1R2
        source: msstore
    
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: noSqlWorkbenchPackage
      directives:
        description: Install Amazon NoSQL Workbench
      settings:
        id: Amazon.NoSQLWorkbench
        source: winget
    
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: sqlServerManagementStudioPackage
      directives:
        description: Install Microsoft SQL Server Management Studio (SSMS)
      settings:
        id: Microsoft.SQLServerManagementStudio
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: dockerDesktopPackage
      directives:
        description: Install Docker Desktop
        allowPrerelease: false
      settings:
        id: Docker.DockerDesktop
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: obsidianPackage
      directives:
        description: Install Obsidian
        allowPrerelease: false
      settings:
        id: Obsidian.Obsidian
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: shareXPackage
      directives:
        description: Install ShareX
        allowPrerelease: false
      settings:
        id: ShareX.ShareX
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: nugetPackage
      directives:
        description: Install NuGet
        allowPrerelease: false
      settings:
        id: Microsoft.NuGet
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: treeSizePackage
      directives:
        description: Install TreeSize
        allowPrerelease: false
      settings:
        id: JAMSoftware.TreeSize.Free
        source: winget
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: winMergePackage
      directives:
        description: Install WinMerge
        allowPrerelease: false
      settings:
        id: WinMerge.WinMerge
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: powerShellPackage
      directives:
        description: Install PowerShell
        allowPrerelease: false
      settings:
        id: Microsoft.PowerShell
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ohMyPoshPackage
      directives:
        description: Install OhMyPosh
        allowPrerelease: false
      settings:
        id: JanDeDobbeleer.OhMyPosh
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: 7zipPackage
      directives:
        description: Install 7zip
        allowPrerelease: false
      settings:
        id: 7zip.7zip
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: gIMPPackage
      directives:
        description: Install GIMP
        allowPrerelease: false
      settings:
        id: GIMP.GIMP
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: oBSStudioPackage
      directives:
        description: Install OBSStudio
        allowPrerelease: false
      settings:
        id: OBSProject.OBSStudio
        source: winget
        
  configurationVersion: 0.2.0
